# Generated by Django 5.1.4 on 2024-12-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.IntegerField()),
                ('device_type', models.CharField(max_length=50)),
                ('column_1', models.CharField(blank=True, max_length=255, null=True)),
                ('column_2', models.CharField(blank=True, max_length=255, null=True)),
                ('column_3', models.CharField(blank=True, max_length=255, null=True)),
                ('column_4', models.CharField(blank=True, max_length=255, null=True)),
                ('column_5', models.CharField(blank=True, max_length=255, null=True)),
                ('column_6', models.CharField(blank=True, max_length=255, null=True)),
                ('column_7', models.CharField(blank=True, max_length=255, null=True)),
                ('column_8', models.CharField(blank=True, max_length=255, null=True)),
                ('column_9', models.CharField(blank=True, max_length=255, null=True)),
                ('column_10', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'devices',
            },
        ),
    ]
