# Generated by Django 5.1.4 on 2024-12-16 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_push', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data',
            table='customers',
        ),
    ]
