# Generated by Django 5.1.4 on 2024-12-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_push', '0002_alter_data_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='name',
        ),
        migrations.RemoveField(
            model_name='data',
            name='value',
        ),
        migrations.AddField(
            model_name='data',
            name='email',
            field=models.EmailField(default='na', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='first_name',
            field=models.CharField(default='na', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='gender',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='ip_address',
            field=models.GenericIPAddressField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
